import { describe, it, expect } from "vitest";
import { parser } from "../../../src/plugins/math/grammar.ts";
import type { MathNode } from "../../../src/plugins/math/types.ts";

function parse(input: string): MathNode { return parser.parse("Expression", input) as MathNode; }
function num(value: number) { return { type: "NumberLiteral", value }; }
function id(name: string, prefix = "plain") { return { type: "Identifier", name, prefix }; }
function bin(op: string, left: object, right: object) { return { type: "BinaryExpression", operator: op, left, right }; }
function unary(op: string, operand: object) { return { type: "UnaryExpression", operator: op, operand }; }
function call(callee: object, args: object[]) { return { type: "CallExpression", callee, args }; }
function control(name: string, args: object[]) { return { type: "ControlExpression", name, args }; }
function subscript(base: object, sub: object) { return { type: "SubscriptExpression", base, subscript: sub }; }

describe("Numbers", () => { it("integer", () => { expect(parse("42")).toMatchObject(num(42)); }); it("decimal", () => { expect(parse("3.14")).toMatchObject(num(3.14)); }); it("leading dot", () => { expect(parse(".5")).toMatchObject(num(0.5)); }); });
describe("Identifiers", () => { it("plain", () => { expect(parse("x")).toMatchObject(id("x")); }); it("left-skew", () => { expect(parse("`a")).toMatchObject(id("a", "left-skew")); }); it("right-skew", () => { expect(parse("`1T")).toMatchObject(id("T", "right-skew")); }); it("greek", () => { expect(parse("\\a")).toMatchObject(id("a", "greek")); }); it("greek-right", () => { expect(parse("\\1b")).toMatchObject(id("b", "greek-right")); }); it("blackboard", () => { const n = parse("\\\\R") as any; expect(n.prefix).toBe("blackboard"); expect(n.name).toBe("R"); }); });
describe("Additive", () => { it("add", () => { expect(parse("a+b")).toMatchObject(bin("+", id("a"), id("b"))); }); it("sub", () => { expect(parse("a-b")).toMatchObject(bin("-", id("a"), id("b"))); }); it("left-assoc", () => { expect(parse("a+b+c")).toMatchObject(bin("+", bin("+", id("a"), id("b")), id("c"))); }); });
describe("Multiplicative", () => { it("explicit", () => { expect(parse("a*b")).toMatchObject(bin("*", id("a"), id("b"))); }); it("division", () => { expect(parse("a/b")).toMatchObject(bin("/", id("a"), id("b"))); }); it("implicit 2x", () => { expect(parse("2x")).toMatchObject(bin("*", num(2), id("x"))); }); it("dot", () => { expect(parse("u.v")).toMatchObject(bin(".", id("u"), id("v"))); }); it("regression: (3+5) not 3*(+5)", () => { const n = parse("2*(3+5)") as any; expect(n.right.operator).toBe("+"); }); });
describe("Power", () => { it("basic", () => { expect(parse("x^2")).toMatchObject(bin("^", id("x"), num(2))); }); it("right-assoc", () => { expect(parse("x^2^3")).toMatchObject(bin("^", id("x"), bin("^", num(2), num(3)))); }); });
describe("Unary", () => { it("neg", () => { expect(parse("-x")).toMatchObject(unary("-", id("x"))); }); it("double", () => { expect(parse("--x")).toMatchObject(unary("-", unary("-", id("x")))); }); });
describe("Postfix", () => { it("call", () => { expect(parse("f(x)")).toMatchObject(call(id("f"), [id("x")])); }); it("subscript", () => { expect(parse("x_i")).toMatchObject(subscript(id("x"), id("i"))); }); it("control", () => { expect(parse("\\int{0,1,x}")).toMatchObject(control("int", [num(0), num(1), id("x")])); }); it("factorial", () => { const n = parse("n!") as any; expect(n.type).toBe("FactorialExpression"); }); it("factorial vs !=", () => { expect((parse("x != y") as any).operator).toBe("!="); }); it("derivative", () => { const n = parse("f'") as any; expect(n.type).toBe("Derivative"); expect(n.order).toBe(1); }); it("index", () => { const n = parse("A[k]") as any; expect(n.type).toBe("IndexExpression"); }); });
describe("Relational", () => { it("=", () => { expect(parse("a = b")).toMatchObject(bin("=", id("a"), id("b"))); }); it("!=", () => { expect(parse("a != b")).toMatchObject(bin("!=", id("a"), id("b"))); }); it("<=", () => { expect(parse("a <= b")).toMatchObject(bin("<=", id("a"), id("b"))); }); it("->", () => { expect(parse("x -> a")).toMatchObject(bin("->", id("x"), id("a"))); }); it("precedence", () => { expect(parse("a+1=b")).toMatchObject(bin("=", bin("+", id("a"), num(1)), id("b"))); }); });
describe("SubSuperscript", () => { it("x_i^2", () => { const n = parse("x_i^2") as any; expect(n.type).toBe("SubSuperscriptExpression"); }); });
describe("Bracket", () => { it("[a] vector", () => { expect((parse("[a]") as any).type).toBe("VectorName"); }); it("[a,b,c] row", () => { const n = parse("[a,b,c]") as any; expect(n.type).toBe("Matrix"); expect(n.rows[0]).toHaveLength(3); }); it("[[a,b],[c,d]] matrix", () => { const n = parse("[[a,b],[c,d]]") as any; expect(n.rows).toHaveLength(2); }); it("(a,b,c) col", () => { const n = parse("(a,b,c)") as any; expect(n.type).toBe("Matrix"); expect(n.rows).toHaveLength(3); }); });
describe("Misc", () => { it("|x| abs", () => { expect((parse("|x|") as any).type).toBe("AbsoluteValue"); }); it("rollout +", () => { const n = parse("+{k=0,n,A[k]}") as any; expect(n.type).toBe("ControlExpression"); expect(n.name).toBe("+"); }); it("ellipsis", () => { expect((parse("...") as any).type).toBe("Ellipsis"); }); });
describe("Errors", () => { it("empty", () => { expect(() => parse("")).toThrow(); }); it("unmatched paren", () => { expect(() => parse("(a+b")).toThrow(); }); });
