import { describe, it, expect } from "vitest";
import { renderMath } from "../../../src/plugins/math/render.ts";
import { parser } from "../../../src/plugins/math/grammar.ts";
import type { MathNode } from "../../../src/plugins/math/types.ts";

function html(input: string): string { return renderMath(parser.parse("Expression", input) as MathNode).innerHTML; }
function query(input: string, sel: string) { return renderMath(parser.parse("Expression", input) as MathNode).querySelector(sel); }

describe("Render — basics", () => { it("number", () => { expect(html("42")).toContain("42"); }); it("identifier class", () => { expect(query("x", ".ident-plain")).not.toBeNull(); }); it("greek glyph", () => { expect(html("\\a")).toContain("α"); }); it("blackboard", () => { expect(html("\\\\R")).toContain("ℝ"); }); it("hebrew", () => { expect(html("\\ha")).toContain("ℵ"); }); });
describe("Render — binary", () => { it("fraction", () => { expect(query("a/b", ".fraction")).not.toBeNull(); }); it("power sup", () => { expect(query("x^2", "sup")).not.toBeNull(); }); it("+ text", () => { expect(html("a+b")).toContain("+"); }); it("dot ·", () => { expect(html("u.v")).toContain("·"); }); it("!= ≠", () => { expect(html("a != b")).toContain("≠"); }); it("<= ≤", () => { expect(html("a <= b")).toContain("≤"); }); it("-> →", () => { expect(html("x -> a")).toContain("→"); }); });
describe("Render — multiply sign", () => { it("2*3 shows ×", () => { expect(html("2*3")).toContain("×"); }); it("2*x hides", () => { expect(html("2*x")).not.toContain("×"); }); it("x*y hides", () => { expect(html("x*y")).not.toContain("×"); }); it("(a+b)*3 hides", () => { expect(html("(a+b)*3")).not.toContain("×"); }); it("2*(a+b) hides", () => { expect(html("2*(a+b)")).not.toContain("×"); }); });
describe("Render — structures", () => { it("integral", () => { expect(query("\\int{0,1,x}", ".integral")).not.toBeNull(); }); it("integral body beside", () => { expect(query("\\int{0,1,x}", ".opstack .integral-body")).toBeNull(); }); it("sqrt", () => { expect(query("\\sqrt{x}", ".sqrt")).not.toBeNull(); }); it("subsuperscript", () => { expect(query("x_i^2", ".subsuperscript")).not.toBeNull(); }); it("vector arrow", () => { expect(html("[a]")).toContain("⃗"); }); it("matrix", () => { expect(query("[[a,b],[c,d]]", ".matrix")).not.toBeNull(); }); it("abs |", () => { expect(html("|x|")).toContain("|"); }); it("norm ‖", () => { expect(html("|[a]|")).toContain("‖"); }); it("factorial", () => { expect(html("n!")).toContain("!"); }); it("derivative", () => { expect(html("f'")).toContain("′"); }); it("ellipsis", () => { expect(html("...")).toContain("…"); }); it("floor", () => { expect(html("\\floor{x}")).toContain("⌊"); }); it("ceil", () => { expect(html("\\ceil{x}")).toContain("⌈"); }); it("inner", () => { expect(html("\\inner{x,y}")).toContain("⟨"); }); it("Σ", () => { expect(html("\\S{k,n,k}")).toContain("Σ"); }); it("lim", () => { expect(html("\\lim{x,f(x)}")).toContain("lim"); }); });
describe("Render — parens", () => { it("(a+b)*c has (", () => { expect(html("(a+b)*c")).toContain("("); }); it("renderMath wraps", () => { expect(renderMath(parser.parse("Expression", "x") as MathNode).className).toBe("native-math"); }); });
